# Generated by Django 3.1.2 on 2020-10-23 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('friends', models.ManyToManyField(related_name='_person_friends_+', to='users.Person')),
            ],
        ),
    ]
